### PR TITLE
Fixes gradle task

### PR DESCRIPTION
**Pull request by nerdoza**
Checks config prior to setting minSdkVersion to resolve issue when cdvMinSdkVersion is not set prior to gradle task.

### CODE REVIEW

**Comment by jpierront** [comment]
Thanks! Any way to use this fork easily ? (Because the package.json is in a sub directory)

**Comment by nerdoza** [comment]
@jpierront, there is a branch on my repo called `PluginOnly` which has the plugin as the root directory.

**Comment by jpierront** [comment]
I did the same thing on my side this weekend, too bad not to have a simpler solution :) Thank you!

**Comment by nerdoza** [comment]
@iainmcgin, is there a reason this hasn't been pulled in yet?

**Comment by iainmcgin** [comment]
I no longer work for Google and there is no active maintainer for this project. I will enquire about forking this project to the OpenID Foundation, as it was primarily built for the purposes of AppAuth-JS.

**Comment by sandervankasteel** [comment]
Any update on forking this project to the OpenID Foundation @iainmcgin ?

**Pull request closed without merging**
